version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=blog
    networks:
      - blog-net
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
  spring-site:
    container_name: spring-boot
    depends_on:
      - postgres-db
    build: ./BlogSite
    restart: on-failure
    networks:
      - blog-net
    ports:
      - 8080:8080
    volumes:
      - spring-data:/root/.m2
    stdin_open: true
    tty: true
  vue-app:
    container_name: vue-3
    depends_on:
      - postgres-db
    build: ./blog-app
    restart: on-failure
    networks:
      - blog-net
    ports:
      - 3000:3000
    volumes:
      - vue-data:/app
    tty: true
volumes:
  spring-data:
  vue-data:
networks:
  blog-net:
    driver: bridge